DROP TABLE IF EXISTS loans;

CREATE TABLE LOANS(
  LOAN_ID VARCHAR(10) PRIMARY KEY
 ,CUSTOMER_ID VARCHAR(10) NOT NULL
 ,LENDER_ID VARCHAR(10) NOT NULL
 ,AMOUNT DOUBLE NOT NULL
 ,REMAINING_AMOUNT DOUBLE NOT NULL
 ,PAYMENT_DATE DATE NOT NULL
 ,`INTEREST_PER_DAY` VARCHAR(10) NOT NULL
 ,DUE_DATE DATE NOT NULL
 ,`PENALTY_PER_DAY` VARCHAR(10) NOT NULL
);

